import { INavData } from '@coreui/angular';

export const navItems: INavData[] = [
  {
    name: 'Dashboard',
    url: '/dashboard',
    iconComponent: { name: 'cil-speedometer' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Métricas Globales',
    url: '/metrics',
    iconComponent: { name: 'cil-chart-pie' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    title: true,
    name: 'Operaciones Comerciales',
  },
  {
    name: 'Ventas',
    url: '/sales',
    iconComponent: { name: 'cil-cart' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Facturación & NCF',
    url: '/billing',
    iconComponent: { name: 'cil-notes' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Servicios',
    url: '/services',
    iconComponent: { name: 'cil-briefcase' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Caja',
    url: '/cash-register',
    iconComponent: { name: 'cil-calculator' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Cobros',
    url: '/receivables',
    iconComponent: { name: 'cil-dollar' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Notas de Crédito',
    url: '/credit-notes',
    iconComponent: { name: 'cil-description' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Clientes',
    url: '/customers',
    iconComponent: { name: 'cil-user' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    title: true,
    name: 'Inventario & Almacenes',
  },
  {
    name: 'Control de Stock',
    url: '/inventory/stock',
    iconComponent: { name: 'cil-storage' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Entradas de Almacén',
    url: '/inventory/entries',
    iconComponent: { name: 'cil-arrow-right' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Salidas de Almacén',
    url: '/inventory/outlets',
    iconComponent: { name: 'cil-arrow-left' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Transferencias',
    url: '/inventory/transfers',
    iconComponent: { name: 'cil-swap-horizontal' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Almacenes & Depósitos',
    url: '/inventory/warehouses',
    iconComponent: { name: 'cil-home' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Autorizaciones / Auditoría',
    url: '/inventory/manage-requests',
    iconComponent: { name: 'cil-check-circle' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Catálogo de Productos',
    url: '/products',
    iconComponent: { name: 'cil-layers' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Categorías y Tipos',
    url: '/products/settings',
    iconComponent: { name: 'cil-settings' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    title: true,
    name: 'Compras & Proveedores',
  },
  {
    name: 'Proveedores',
    url: '/purchases/suppliers',
    iconComponent: { name: 'cil-contact' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Órdenes de Compra',
    url: '/purchases',
    iconComponent: { name: 'cil-truck' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Recepciones de Mercancía',
    url: '/purchases/receipts',
    iconComponent: { name: 'cil-task' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Pagos a Proveedores',
    url: '/payments',
    iconComponent: { name: 'cil-credit-card' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    title: true,
    name: 'Administración',
  },
  {
    name: 'Mi Perfil',
    url: '/profile',
    iconComponent: { name: 'cil-user' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Usuarios y Equipo',
    url: '/users',
    iconComponent: { name: 'cil-people' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Roles y Permisos',
    url: '/admin/roles',
    iconComponent: { name: 'cil-shield-alt' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Matriz de Permisos',
    url: '/admin/roles/matrix',
    iconComponent: { name: 'cil-grid' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Bandeja de Aprobaciones',
    url: '/admin/approvals',
    iconComponent: { name: 'cil-check' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
  {
    name: 'Configuración de Empresa',
    url: '/company/settings',
    iconComponent: { name: 'cil-building' },
    linkProps: { routerLinkActiveOptions: { exact: true } },
  },
];
