import {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowLeft,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilContrast,
  cilCopy,
  cilCreditCard,
  cilCursor,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilExternalLink,
  cilFile,
  cilGrid,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMediaRecord,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilSwapHorizontal,
  cilCart,
  cilTruck,
  cilBuilding,
  cilTransfer,
  cilArrowThickFromBottom,
  cilArrowThickToBottom,
  cilPlus,
  cilSearch,
  cilZoom,
  cilX,
  cilWarning,
  cilCheckCircle,
  cilStorage,
  cilFilter,
  cilChevronTop,
  cilBank,
  cilShieldAlt,
  cilReload,
  cilBriefcase,
  cilContact,
  cilMoney,
  cilClock,
  cilPhone,
  cilLockUnlocked,
  cilHandshake,
  cilAddressBook,
  cilWallet,
  cilCash
} from '@coreui/icons';

export const cilWrench = [
  '512 512',
  '<path fill="currentColor" d="M501.1 395.7L386.4 281c-4-4-10.5-4.1-14.7-.2l-37.3 37.3c-4 4-3.9 10.7.2 14.7l114.7 114.7c15.6 15.6 40.9 15.6 56.6 0s15.6-40.9-.2-56.6zM224 136c0-49.7 32.4-91.9 77.3-106.1 6.4-2 9.5-9.2 6.9-15.3-7.6-17.6-26.6-29.3-48.2-29.3-79.5 0-144 64.5-144 144 0 28.5 8.4 55.1 22.8 77.4L10.3 334.9c-13.7 13.7-13.7 36.1 0 49.8l117 117c13.7 13.7 36.1 13.7 49.8 0l128.2-128.2c22.3 14.4 48.9 22.8 77.4 22.8 79.5 0 144-64.5 144-144 0-21.6-11.7-40.6-29.3-48.2-6.1-2.6-13.3.5-15.3 6.9C368.6 256.3 326.4 288.7 276.7 288.7 200.2 288.7 136 224.5 136 148c0-4.1.3-8.1.8-12H224z"/>'
];

import { signet } from './signet';
import { logo } from './logo';

export const iconSubset = {
  cilWrench,
  'cil-wrench': cilWrench,
  cilReload,
  'cil-reload': cilReload,
  cilBank,
  cilShieldAlt,
  'cil-shield-alt': cilShieldAlt,
  cilSwapHorizontal,
  cilCart,
  cilTruck,
  cilBuilding,
  cilTransfer,
  cilArrowThickFromBottom,
  cilArrowThickToBottom,
  cilPlus,
  cilSearch,
  cilZoom,
  cilX,
  cilWarning,
  cilCheckCircle,
  cilStorage,
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowLeft,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilContrast,
  cilCopy,
  cilCreditCard,
  cilCursor,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilExternalLink,
  cilFile,
  cilGrid,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMediaRecord,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilFilter,
  cilChevronTop,
  cilBriefcase,
  'cil-briefcase': cilBriefcase,
  cilContact,
  'cil-contact': cilContact,
  cilMoney,
  'cil-money': cilMoney,
  cilClock,
  'cil-clock': cilClock,
  cilPhone,
  'cil-phone': cilPhone,
  cilLockUnlocked,
  'cil-lock-unlocked': cilLockUnlocked,
  cilHandshake,
  'cil-handshake': cilHandshake,
  cilAddressBook,
  'cil-address-book': cilAddressBook,
  cilWallet,
  'cil-wallet': cilWallet,
  cilCash,
  'cil-cash': cilCash,
  'cil-cart': cilCart,
  'cil-notes': cilNotes,
  'cil-calculator': cilCalculator,
  'cil-storage': cilStorage,
  'cil-arrow-right': cilArrowRight,
  'cil-arrow-left': cilArrowLeft,
  'cil-swap-horizontal': cilSwapHorizontal,
  'cil-home': cilHome,
  'cil-check-circle': cilCheckCircle,
  'cil-layers': cilLayers,
  'cil-settings': cilSettings,
  'cil-truck': cilTruck,
  'cil-task': cilTask,
  'cil-credit-card': cilCreditCard,
  'cil-people': cilPeople,
  'cil-grid': cilGrid,
  'cil-check': cilCheck,
  'cil-building': cilBuilding,
  'cil-speedometer': cilSpeedometer,
  'cil-chart-pie': cilChartPie,
  'cil-dollar': cilDollar,
  'cil-description': cilDescription,
  'cil-user': cilUser,
  logo,
  signet
};

export enum IconSubset {
  cibCcAmex = 'cibCcAmex',
  cibCcApplePay = 'cibCcApplePay',
  cibCcMastercard = 'cibCcMastercard',
  cibCcPaypal = 'cibCcPaypal',
  cibCcStripe = 'cibCcStripe',
  cibCcVisa = 'cibCcVisa',
  cibFacebook = 'cibFacebook',
  cibGoogle = 'cibGoogle',
  cibLinkedin = 'cibLinkedin',
  cibSkype = 'cibSkype',
  cibTwitter = 'cibTwitter',
  cifBr = 'cifBr',
  cifEs = 'cifEs',
  cifFr = 'cifFr',
  cifIn = 'cifIn',
  cifPl = 'cifPl',
  cifUs = 'cifUs',
  cilAccountLogout = 'cilAccountLogout',
  cilAlignCenter = 'cilAlignCenter',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowLeft = 'cilArrowLeft',
  cilArrowRight = 'cilArrowRight',
  cilArrowTop = 'cilArrowTop',
  cilBasket = 'cilBasket',
  cilBell = 'cilBell',
  cilBold = 'cilBold',
  cilBookmark = 'cilBookmark',
  cilCalculator = 'cilCalculator',
  cilCalendar = 'cilCalendar',
  cilChart = 'cilChart',
  cilChartPie = 'cilChartPie',
  cilCheck = 'cilCheck',
  cilChevronLeft = 'cilChevronLeft',
  cilChevronRight = 'cilChevronRight',
  cilCloudDownload = 'cilCloudDownload',
  cilCode = 'cilCode',
  cilCommentSquare = 'cilCommentSquare',
  cilContrast = 'cilContrast',
  cilCreditCard = 'cilCreditCard',
  cilCursor = 'cilCursor',
  cilDescription = 'cilDescription',
  cilDollar = 'cilDollar',
  cilDrop = 'cilDrop',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilExternalLink = 'cilExternalLink',
  cilFile = 'cilFile',
  cilGrid = 'cilGrid',
  cilHome = 'cilHome',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilLanguage = 'cilLanguage',
  cilLayers = 'cilLayers',
  cilList = 'cilList',
  cilListNumbered = 'cilListNumbered',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMap = 'cilMap',
  cilMediaPlay = 'cilMediaPlay',
  cilMediaRecord = 'cilMediaRecord',
  cilMenu = 'cilMenu',
  cilMoon = 'cilMoon',
  cilNotes = 'cilNotes',
  cilOptions = 'cilOptions',
  cilPaperclip = 'cilPaperclip',
  cilPaperPlane = 'cilPaperPlane',
  cilPen = 'cilPen',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPrint = 'cilPrint',
  cilPuzzle = 'cilPuzzle',
  cilReportSlash = 'cilReportSlash',
  cilSave = 'cilSave',
  cilSettings = 'cilSettings',
  cilShare = 'cilShare',
  cilShareAll = 'cilShareAll',
  cilShareBoxed = 'cilShareBoxed',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilStar = 'cilStar',
  cilSun = 'cilSun',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTrash = 'cilTrash',
  cilUnderline = 'cilUnderline',
  cilUser = 'cilUser',
  cilUserFemale = 'cilUserFemale',
  cilUserFollow = 'cilUserFollow',
  cilUserUnfollow = 'cilUserUnfollow',
  cilStorage = 'cilStorage',
  cilWrench = 'cilWrench',
  cilReload = 'cilReload',
  cilBank = 'cilBank',
  cilShieldAlt = 'cilShieldAlt',
  cilBriefcase = 'cilBriefcase',
  cilContact = 'cilContact',
  cilMoney = 'cilMoney',
  cilClock = 'cilClock',
  cilPhone = 'cilPhone',
  cilLockUnlocked = 'cilLockUnlocked',
  cilHandshake = 'cilHandshake',
  cilAddressBook = 'cilAddressBook',
  cilWallet = 'cilWallet',
  cilCash = 'cilCash',
  logo = 'logo',
  signet = 'signet'
}
